### ISSUE TITLE
Incorrectly emitting -msse4

### ISSUE THREAD

**Issue by marwuint** [hartwork/resolve-march-native#197]
The script emits the following flags for my Intel Core2 P8600:
`-march=core2 -msse4 -msse4.1 -mxsave --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=3072`
Which looks fine at first glance, except that `-msse4` enables unsupported popcnt and sse4.2, [at least in gcc](https://doktobune.wordpress.com/2010/07/17/be-careful-with-the-gcc-flag-msse4/), although it doesn't seem to be well documented.

[lscpu output](https://github.com/user-attachments/files/18129333/meow.txt)
[gcc's resolution of -march=core2 -msse4](https://github.com/user-attachments/files/18129399/qq.txt)

**Comment by hartwork** [comment]
Hi @marwuint, which version of resolve-march-native is this with? In particular, there was a related pull request #180 that went into [release 5.1.0](https://github.com/hartwork/resolve-march-native/releases/tag/5.1.0). Please help me understand the situation better.

**Comment by marwuint** [comment]
Sorry, i've just checked the closed issues. I was using v5.0.2.

**Comment by hartwork** [comment]
@marwuint so 5.1.0 works well for you and we can close as working alright?

**Comment by marwuint** [comment]
Yes, v5.1 does work correctly.

**Comment by hartwork** [comment]
@marwuint perfect, thanks for the update! :+1:
