### ISSUE TITLE
Determine --param=l?-cache-*size

### ISSUE THREAD

**Issue by Massimo-B** [hartwork/resolve-march-native#45]
```
grep "model name" /proc/cpuinfo |head -1
model name      : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

resolve-march-native --keep-identical-mtune  --vertical |grep cache
--param=l1-cache-line-size=64
--param=l1-cache-size=32
--param=l2-cache-size=8192
```
How are the cache sizes determined, just from gcc defaults?
I'm not sure if these values are correct.

At least here I read different values:
https://www.cpu-world.com/CPUs/Core_i7/Intel-Core%20i7-3770.html
```
Level 1 cache size  | 4 x 32 KB 8-way set associative instruction caches 4 x 32 KB 8-way set associative data caches
Level 2 cache size  | 4 x 256 KB 8-way set associative caches
Level 3 cache size | 8 MB 16-way set associative shared cache
```

### Background
I need this tool to determine the explicit flags behind -march=native in order to pass them via distcc to remote servers that can't detect them.

**Comment by hartwork** [comment]
Hi @Massimo-B those values are obtained right from GCC output. The only other "magic" done in here is a set of three values (below) that are considered the original defaults (and taken from GCC sources, AFAIR) and hence not produced (for brevity) unless you pass `--keep-default-params` on the command line, explicitly. 

https://github.com/hartwork/resolve-march-native/blob/acfc87875e19ae9d4b0e5c9de1d21bc259415336/resolve_march_native/engine.py#L56-L60

So you should be able to trust resolve-march-native's output as much as GCC with regard to those cache sizes.

Does that answer the question?

**Comment by hartwork** [comment]
I'm starting to think that these hard-coded defaults were a mistake, they seem dynamic now at a quick look:

```console
# git --no-pager grep l1-cache-line-size -- gcc/config/
gcc/config/i386/driver-i386.cc:     "--param l1-cache-line-size=%u ", level1.line);
gcc/config/rs6000/driver-rs6000.cc:  sprintf (line, "--param l1-cache-line-size=%u", l1_line);
```

So I'm considering to drop these defaults and to drop argument `--keep-default-params` now. What do you think?

**Comment by Massimo-B** [comment]
I'm not sure. Here I don't see any difference when using `--keep-default-params`.

**Comment by hartwork** [comment]
There is PR #49 now. Review and testing is welcome.
