### ISSUE TITLE
`ERROR: Line '  -mabi=ABI                   \t\tlp64' not understood`

### ISSUE THREAD

**Issue by StuartIanNaylor** [hartwork/resolve-march-native#72]
Just installed on a Arm A53 board running ubuntu via pip.
```
orangepi@orangepizero2:~$ resolve-march-native
ERROR: Line '  -mabi=ABI                   \t\tlp64' not understood
```
Haven't really looked into what could be the cause but just feedback.

**Comment by hartwork** [comment]
Hi @StuartIanNaylor, thanks for the report! :+1: 

Which version of Ubuntu and GCC is this? Could you share the output of?:
- `cat /etc/os-release`
- `gcc --version`

Could you give pull request #73 a try?

Thanks and best, Sebastian

**Comment by StuartIanNaylor** [comment]
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
gcc (Debian 8.3.0-6) 8.3.0
```

**Comment by hartwork** [comment]
@StuartIanNaylor thanks! Any chance you could try pull request #73? Please let me know if shell commands to ease testing would help.

**Comment by hartwork** [comment]
@StuartIanNaylor any news?

**Comment by StuartIanNaylor** [comment]
Apols I totally forgot, haven't even got that OS setup anymore.
