### ISSUE TITLE
Support for `-mcpu`

### ISSUE THREAD

**Issue by Richard-Rogalski** [hartwork/resolve-march-native#78]
On many architectures, `-mcpu` is the functional equivalent of `-march`, and `-march` is unavailable. Nope, and there's not even a good reason as to why :)

On these architectures, GCC outputs `gcc: error: unrecognized command-line option '-march=native'; did you mean '-mcpu=native'?`, so this would be a good way to check which flag to use. 

I tried implementing this myself, but I don't know python and couldn't even figure out how to build this or run it or what to do (^: python scares me. But, I imagine it won't be tooo troublesome :D.

To test, you're welcome to have SSH access to either ppc64el or sparc64, whichever one interests you more :>

**Comment by Richard-Rogalski** [comment]
Or, of course, if you walk me through a bit on how to actually make the main executable, I'd take a crack again :)

**Comment by hartwork** [comment]
@Richard-Rogalski one way to build from Git would be:
```console
# cd "$(mktemp -d)"
# git clone https://github.com/hartwork/resolve-march-native
# cd resolve-march-native/
# python3 -m venv venv
# source venv/bin/activate
# pip install -e .
# which resolve-march-native
/tmp/tmp.xakGIHT44e/resolve-march-native/venv/bin/resolve-march-native
# resolve-march-native --version
resolve-march-native 2.2.0
```

**Comment by Richard-Rogalski** [comment]
> `-mcpu=` is told to me as deprecated by e.g. GCC 11:
It is on amd64. Its meaning varies across the arches. On arches where `-march` is available, it is a deprecated alias to either `-march` or `-mtune`.

However, on some arches it's not an alias, `march` doesn't exist and it's basically just what `march` is called, and it's in no means deprecated. It doesn't make sense, it's that way because legacy reasons and stuff.

I'll give it a crack :) thanks!!

**Comment by hartwork** [comment]
@Richard-Rogalski can you prove that it's not deprecated for GCC 11+ on other arches? Any links?

**Comment by Richard-Rogalski** [comment]
https://gcc.gnu.org/onlinedocs/gcc/SPARC-Options.html

https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

ctrl+f `march` and `mcpu` on both of those :)

**Comment by hartwork** [comment]
@Richard-Rogalski thanks! :+1:

**Comment by hartwork** [comment]
@Richard-Rogalski any chance you could give pull request #107 a try? The description there includes commands to ease running code off the branch behind it. Thanks in advance!

**Comment by Richard-Rogalski** [comment]
Sure, I can try this on my ppc64le machine, I cannot test on the sparc for the forseeable future tho

**Comment by hartwork** [comment]
@Richard-Rogalski I understand. Thanks for your reply at https://github.com/hartwork/resolve-march-native/pull/107#issuecomment-1789694705 and for for testing on ppc64le! :+1:

**Comment by Richard-Rogalski** [comment]
if that was the expected response, I'm glad :) thanks a bunch!!
I guess -mcpu=power8 covers everything already, then

**Comment by hartwork** [comment]
@Richard-Rogalski I'm good, let's just do what we can, best effort. I'm optimistic that #107 can be merged soon, let me re-open this issue while it's not merged yet. If all goes well, it will be closed soon and be part of a new release also.
